name: Continuos Integration

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - master
  release:
    types:
      - prereleased
      - created

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.10

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false
      
      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.26.0

      - name: Check linting of Terraform files
        id: lint
        run: tflint

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Install TFSec
        run: |
          curl -L https://github.com/tfsec/tfsec/releases/download/v0.39.20/tfsec-linux-amd64 -o tfsec && \
          sudo chmod +x tfsec && \
          sudo mv tfsec /usr/local/bin/tfsec

      - name: TFSec
        id: sec
        run: tfsec

      - name: Install Terraform Docs
        run: |
          curl -L https://github.com/terraform-docs/terraform-docs/releases/download/v0.12.1/terraform-docs-v0.12.1-$(uname)-amd64.tar.gz -o terraform-docs.tar.gz && \
          tar -xzf terraform-docs.tar.gz && \
          sudo chmod +x terraform-docs && \
          sudo mv terraform-docs /usr/local/bin/terraform-docs
      
      #- name: Terraform Docs
      #  id: docs
      #  run: #TO DO
